# Generated by Django 5.1.2 on 2024-10-13 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csr', '0007_alter_gasutilservicerequest_resolved_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasutilservicerequest',
            name='resolved_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 8, 14, 29, 464636, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gasutilservicerequest',
            name='service_paid_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 8, 14, 29, 464636, tzinfo=datetime.timezone.utc)),
        ),
    ]
